"""empty message

Revision ID: 7131b0e93ef4
Revises: fa60a2ed87f5
Create Date: 2026-03-20 22:04:18.373074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7131b0e93ef4'
down_revision = '978c94e29e6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('dia_recebimento', sa.Integer(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registro_receita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('receita_id', sa.Integer(), nullable=False),
    sa.Column('data_recebimento_esperada', sa.Date(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('recebido', sa.Boolean(), nullable=False),
    sa.Column('data_recebimento', sa.Date(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['receita_id'], ['receita.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receita_id', 'data_recebimento_esperada', name='_receita_recebimento_uc')
    )
    with op.batch_alter_table('registro_receita', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registro_receita_data_recebimento_esperada'), ['data_recebimento_esperada'], unique=False)
        batch_op.create_index(batch_op.f('ix_registro_receita_receita_id'), ['receita_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_receita', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registro_receita_receita_id'))
        batch_op.drop_index(batch_op.f('ix_registro_receita_data_recebimento_esperada'))

    op.drop_table('registro_receita')
    op.drop_table('receita')
    # ### end Alembic commands ###
