"""Initial migration

Revision ID: bae5c57e99f5
Revises: 
Create Date: 2026-04-21 16:46:25.675643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bae5c57e99f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_custo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('tipo_combustivel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_id', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('profile_pic', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('abastecimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('km_atual', sa.Integer(), nullable=False),
    sa.Column('litros', sa.Float(), nullable=False),
    sa.Column('valor_litro', sa.Float(), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('tanque_cheio', sa.Boolean(), nullable=True),
    sa.Column('tipo_combustivel_id', sa.Integer(), nullable=True),
    sa.Column('media_consumo_calculada', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['tipo_combustivel_id'], ['tipo_combustivel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('abastecimento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_abastecimento_data'), ['data'], unique=False)

    op.create_table('custo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('dia_vencimento', sa.Integer(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('alerta_dias', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lancamento_diario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('km_rodado', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lancamento_diario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lancamento_diario_data'), ['data'], unique=False)

    op.create_table('parametros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('modelo_carro', sa.String(length=100), nullable=True),
    sa.Column('placa_carro', sa.String(length=20), nullable=True),
    sa.Column('km_atual', sa.Integer(), nullable=True),
    sa.Column('media_consumo', sa.Float(), nullable=True),
    sa.Column('meta_faturamento', sa.Float(), nullable=True),
    sa.Column('periodicidade_meta', sa.String(length=20), nullable=True),
    sa.Column('tipo_meta', sa.String(length=20), nullable=True),
    sa.Column('dias_trabalho_semana', sa.Integer(), nullable=True),
    sa.Column('valor_km_minimo', sa.Float(), nullable=True),
    sa.Column('valor_km_meta', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('dia_recebimento', sa.Integer(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custo_variavel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lancamento_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria_custo.id'], ),
    sa.ForeignKeyConstraint(['lancamento_id'], ['lancamento_diario.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('custo_variavel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custo_variavel_data'), ['data'], unique=False)

    op.create_table('faturamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lancamento_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('fonte', sa.String(length=100), nullable=True),
    sa.Column('origem', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['lancamento_id'], ['lancamento_diario.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faturamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faturamento_data'), ['data'], unique=False)

    op.create_table('registro_custo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('custo_id', sa.Integer(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('pago', sa.Boolean(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('metodo_pagamento', sa.String(length=50), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['custo_id'], ['custo.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custo_id', 'data_vencimento', name='_custo_vencimento_uc')
    )
    with op.batch_alter_table('registro_custo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registro_custo_custo_id'), ['custo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registro_custo_data_vencimento'), ['data_vencimento'], unique=False)

    op.create_table('registro_receita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('receita_id', sa.Integer(), nullable=False),
    sa.Column('data_recebimento_esperada', sa.Date(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('recebido', sa.Boolean(), nullable=False),
    sa.Column('data_recebimento', sa.Date(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['receita_id'], ['receita.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receita_id', 'data_recebimento_esperada', name='_receita_recebimento_uc')
    )
    with op.batch_alter_table('registro_receita', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registro_receita_data_recebimento_esperada'), ['data_recebimento_esperada'], unique=False)
        batch_op.create_index(batch_op.f('ix_registro_receita_receita_id'), ['receita_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_receita', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registro_receita_receita_id'))
        batch_op.drop_index(batch_op.f('ix_registro_receita_data_recebimento_esperada'))

    op.drop_table('registro_receita')
    with op.batch_alter_table('registro_custo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registro_custo_data_vencimento'))
        batch_op.drop_index(batch_op.f('ix_registro_custo_custo_id'))

    op.drop_table('registro_custo')
    with op.batch_alter_table('faturamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faturamento_data'))

    op.drop_table('faturamento')
    with op.batch_alter_table('custo_variavel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custo_variavel_data'))

    op.drop_table('custo_variavel')
    op.drop_table('receita')
    op.drop_table('parametros')
    with op.batch_alter_table('lancamento_diario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lancamento_diario_data'))

    op.drop_table('lancamento_diario')
    op.drop_table('custo')
    with op.batch_alter_table('abastecimento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_abastecimento_data'))

    op.drop_table('abastecimento')
    op.drop_table('user')
    op.drop_table('tipo_combustivel')
    op.drop_table('categoria_custo')
    # ### end Alembic commands ###
